### ISSUE TITLE
Localized item’s `entry_status` is “Standard”

### ISSUE THREAD

**Issue by strogonoff** [glossarist/iev-data#115]
While migrating IEV data to register glossary format, I noticed that items have `entry_status: Standard`.

Our registry schema uses the following statuses, in accordance with ISO 19135-1 (see 6.2 and 7.5.2):

```
const ITEM_STATUSES = [
  'submitted',
  'valid',
  'superseded',
  'retired',
  'invalid',
] as const;
```

Example:

```
pol:
  id: 904-03-14
  terms:
  - type: expression
    normative_status: preferred
    usage_info: systemu
    designation: tryb czuwania
    gender: m
    plurality: singular
  - type: expression
    designation: tryb nieaktywny
    gender: m
    plurality: singular
  language_code: pol
  notes: []
  examples: []
  entry_status: Standard
  review_decision_event: published
```

(cc @ronaldtse)
