### ISSUE TITLE
Parse "modification part" in "clause"

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/iev-data#12]
```
    authoritative_source:
      ref: ISO/IEC Guide 99:2007
      clause: 1.1, modified – Deletion of NOTE 3 and NOTE 4, and some changes in the
        other notes.
      link: https://www.iso.org/standard/45324.html
```

Should be parsed as:
```
    authoritative_source:
      ref: ISO/IEC Guide 99:2007
      clause: 1.1
      modified: Deletion of NOTE 3 and NOTE 4, and some changes in the other notes.
      link: https://www.iso.org/standard/45324.html
```

**Comment by ronaldtse** [comment]
And the french version:
```
      clause: 1.7, modifié – Ajout d'une utilisation spécifique du terme privilégié,
        ajout de renvois dans la définition et la note 4, transfert des exemples 1
        et 2 dans la Note 5 à l'article et ajout d'un nouvel exemple, transfert de
        l'exemple 3 dans une nouvelle Note 6 à l'article
```

**Comment by HassanAkbar** [comment]
I think this has been fixed in https://github.com/glossarist/iev-data/commit/4d6ac190fa3eef554a463384f4de0cad7d4ce7c3. Below is the output for `112-01-01` with latest glossarist model.

```yaml
eng:
  sources:
  - type: authoritative
    status: modified
    origin:
      clause: '1.1'
      link: https://www.iso.org/standard/45324.html
      original: ISO/IEC Guide 99:2007, 1.1, modified – Deletion of NOTE 3 and NOTE
        4, and some changes in the other notes.
    modification: Deletion of NOTE 3 and NOTE 4, and some changes in the other notes.
fra:
  sources:
  - type: authoritative
    status: modified
    origin:
      clause: '1.1'
      link: https://www.iso.org/standard/45324.html
      original: ISO/IEC Guide 99:2007, 1.1, modifié – Suppression de NOTE 3 et NOTE
        4, et quelques modifications dans les autres.
    modification: Suppression de NOTE 3 et NOTE 4, et quelques modifications dans
      les autres.
```

@ronaldtse Let me know if something else needs to be changed?
