### ISSUE TITLE
Lots of weird HTMLs!!

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/iev-data#13]
e.g.
```yaml
  eng:
    id: 1030111
    terms:
    - type: expression
      normativeStatus: preferred
      designation: system of orthogonal functions
    - type: expression
      designation: orthogonal system
    definition: set of functions, such that each of them is orthogonal to any other
    language_code: eng
    notes:
    - "Examples: \n\n<ul> \n\n<li>Legendre polynomials P constitute a system of orthogonal
      functions on the interval $$- 1 ,   + 1$$ because $$∫_(   - 1)^(   + 1) P_k
      \ ( x ) P_l ( x ) dx = 0$$ for any integers $$k != l$$.</li> \n\n<li>Laguerre
      polynomials L constitute a system of orthogonal functions on the interval $$0
      ,   + oo$$ with the weight $$exp ( - x )$$ because $$∫_(  0)^(   + oo ) L_k
      \ ( x ) L_l ( x ) exp ( - x ) dx = 0$$ for any integers $$k != l$$.</li> \n\n<li>Trigonometric
      functions sine and cosine constitute a system of orthogonal functions on the
      interval $$0 ,  2 \\pi$$ because $$∫_(  0)^(  2 \\pi )  sin ( kx ) sin ( lx
      )  dx = 0$$ and $$∫_(  0)^(  2 \\pi )  cos ( kx ) cos ( lx )  dx = 0$$ for any
      integers $$k != l$$, and $$∫_(  0)^(  2 \\pi ) sin ( kx ) cos ( lx )  dx = 0$$
      for any integer $$\x01$$ and $$\x01$$. </li></ul>"
```
