### ISSUE TITLE
IEV 845-23-055: `designation` is parsed into a strange blog

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/iev-data#130]
```yaml
eng:
  id: 845-23-055
  terms:
  - type: expression
    normative_status: preferred
    designation: spectral chromaticity coordinates
  - type: symbol
    designation: |-
      stem:[r](stem:[λ]), stem:[g](stem:[λ]), stem:[b](stem:[λ]), &lt;CIE 1931 RGB colorimetric system&gt; &lt;système de référence colorimétrique CIE 1931&gt;
      stem:[x](stem:[λ]), stem:[y](stem:[λ]), stem:[z](stem:[λ]), &lt;CIE 1931 standard colorimetric system&gt; &lt;système de référence colorimétrique CIE 1931&gt;
      stem:[r]~10~(stem:[λ]), stem:[g]~10~(stem:[λ]), stem:[b]~10~(stem:[λ]), &lt;CIE 1964 RGB colorimetric system&gt; &lt;système de référence colorimétrique CIE 1964&gt;
      stem:[x]~10~(stem:[λ]), stem:[y]~10~(stem:[λ]), stem:[z]~10~(stem:[λ]), &lt;CIE 1964 standard colorimetric system&gt; &lt;système de référence colorimétrique CIE 1964&gt;
    international: true
  definition: chromaticity coordinates of monochromatic stimuli
  language_code: eng
```
