### ISSUE TITLE
Reconcile formats of `related` items and authoritative sources?

### ISSUE THREAD

**Issue by strogonoff** [glossarist/iev-data#142]
Regarding items currently in `related:`, they look like:

```
related:
- ref:
    id: 702-05-17
    source: IEV
    version: 1992-03
  type: supersedes
```

Authoritative sources look like:

```
  authoritative_source:
  - ref: ISO 921:1997
    clause: definition 819
    link: https://www.iso.org/standard/5333.html
    relationship:
      type: modified
    original: ISO 921:1997, definition 819, modified
```

Can we use the same format for both?

cc @ronaldtse
