### ISSUE TITLE
Examples aren't extracted correctly

### ISSUE THREAD

**Issue by skalee** [glossarist/iev-data#154]
Notes are extracted correctly, but examples are not. For example in 102-03-10:

```yaml
eng:
  id: 102-03-10
  terms:
  - type: expression
    normative_status: preferred
    usage_info: of a vector
    designation: component
  definition: |-
    one of a set of linearly independent vectors, the sum of which is equal to a given vector

    EXAMPLE



    * for a given vector stem:[U = U_1 a_1 + U_2 a_2 + ... + U_n a_n], where stem:[U_1 , U_2 , ... , U_n] are the coordinates of *stem:[U]* and stem:[a_1 , a_2 , ... , a_n] are the base vectors, any of the vectors stem:[U_1 a_1 , U_2 a_2 , ... , U_n a_n],

    * the projections of a vector normal and tangential to a surface (normal component and tangential component).
  language_code: eng
  notes:
  - In English, the term "component vector" may be used if "component" is used in
    the sense of "coordinate" (see Note 2 to entry in {{IEV 102-03-09, IEV:102-03-09}}).
  examples: []
```
