### ISSUE TITLE
Missing auth. source?

### ISSUE THREAD

**Issue by strogonoff** [glossarist/iev-data#187]
This is a concept’s YAML obtained from the latest version. It contains no authoritative source. Apparently, there’re no auth. sources from this tool’s output, and therefore no sources on the new [IEV demo site](https://iev.demo.paneron.org/eng/localized-concept/c97e7eb2-bc71-5c0f-bbc1-5c7d61b2336f/item.json).

```yaml
---
termid: 351-50-29
term: holding element
ara:
  id: 351-50-29
  terms:
  - type: expression
    normative_status: preferred
    designation: عنصر حجز
  language_code: ara
  notes: []
  examples: []
  entry_status: valid
  date_accepted: '2013-11-01T00:00:00+00:00'
  date_amended: '2013-11-01T00:00:00+00:00'
  review_date: '2013-11-01T00:00:00+00:00'
  review_decision_date: '2013-11-01T00:00:00+00:00'
  review_decision_event: published
deu:
  id: 351-50-29
  terms:
  - type: expression
    normative_status: preferred
    designation: Halteglied
    gender: n
    plurality: singular
  language_code: deu
  notes: []
  examples: []
  entry_status: valid
  date_accepted: '2013-11-01T00:00:00+00:00'
  date_amended: '2013-11-01T00:00:00+00:00'
  review_date: '2013-11-01T00:00:00+00:00'
  review_decision_date: '2013-11-01T00:00:00+00:00'
  review_decision_event: published
eng:
  id: 351-50-29
  terms:
  - type: expression
    normative_status: preferred
    designation: holding element
  definition: |-
    transfer element in which the output variable is held constant during the time intervals between sampling instants of the input variable

    SEE: Figure 8d).
  language_code: eng
  notes:
  - The time response of a holding element is a stepwise function.
  - This entry was numbered 351-28-40 in IEC 60050-351:2006.
  examples: []
  entry_status: valid
  date_accepted: '2013-11-01T00:00:00+00:00'
  date_amended: '2013-11-01T00:00:00+00:00'
  review_date: '2013-11-01T00:00:00+00:00'
  review_decision_date: '2013-11-01T00:00:00+00:00'
  review_decision_event: published
spa:
  id: 351-50-29
  terms:
  - type: expression
    normative_status: preferred
    designation: elemento de bloqueo
    gender: m
    plurality: singular
  - type: expression
    normative_status: preferred
    designation: bloqueador
    gender: m
    plurality: singular
  language_code: spa
  notes: []
  examples: []
  entry_status: valid
  classification: Preferred
  date_accepted: '2013-11-01T00:00:00+00:00'
  date_amended: '2013-11-01T00:00:00+00:00'
  review_date: '2013-11-01T00:00:00+00:00'
  review_decision_date: '2013-11-01T00:00:00+00:00'
  review_decision_event: published
fin:
  id: 351-50-29
  terms:
  - type: expression
    normative_status: preferred
    designation: pitoelementti
  language_code: fin
  notes: []
  examples: []
  entry_status: valid
  review_decision_event: published
fra:
  id: 351-50-29
  terms:
  - type: expression
    normative_status: preferred
    designation: élément de maintien
    gender: m
    plurality: singular
  definition: |-
    élément de transfert pour lequel la variable de sortie est maintenue constante pendant les intervalles de temps séparant les prises d'échantillon de la variable d'entrée

    VOIR: Figure 8d).
  language_code: fra
  notes:
  - La réponse dans le temps d’un élément de maintien est une fonction en échelons.
  - |-
    Cet article était numéroté 351-28-40 dans la CEI 60050-351:2006.

    image::/assets/images/parts/351/351-fig8.png[Figure 8 - Impulse-function sequence c) and stepwise function d); Séquence de fonctions impulsions c) et fonction en échelons d)]
  examples: []
  entry_status: valid
  date_accepted: '2013-11-01T00:00:00+00:00'
  date_amended: '2013-11-01T00:00:00+00:00'
  review_date: '2013-11-01T00:00:00+00:00'
  review_decision_date: '2013-11-01T00:00:00+00:00'
  review_decision_event: published
ita:
  id: 351-50-29
  terms:
  - type: expression
    normative_status: preferred
    designation: elemento di mantenimento
  language_code: ita
  notes: []
  examples: []
  entry_status: valid
  date_accepted: '2013-11-01T00:00:00+00:00'
  date_amended: '2013-11-01T00:00:00+00:00'
  review_date: '2013-11-01T00:00:00+00:00'
  review_decision_date: '2013-11-01T00:00:00+00:00'
  review_decision_event: published
jpn:
  id: 351-50-29
  terms:
  - type: expression
    normative_status: preferred
    designation: ホールド要素
  language_code: jpn
  notes: []
  examples: []
  entry_status: valid
  date_accepted: '2013-11-01T00:00:00+00:00'
  date_amended: '2013-11-01T00:00:00+00:00'
  review_date: '2013-11-01T00:00:00+00:00'
  review_decision_date: '2013-11-01T00:00:00+00:00'
  review_decision_event: published
kor:
  id: 351-50-29
  terms:
  - type: expression
    normative_status: preferred
    designation: 유지 요소
  language_code: kor
  notes: []
  examples: []
  entry_status: valid
  review_decision_event: published
pol:
  id: 351-50-29
  terms:
  - type: expression
    normative_status: preferred
    designation: element podtrzymujący
  language_code: pol
  notes: []
  examples: []
  entry_status: valid
  date_accepted: '2013-11-01T00:00:00+00:00'
  date_amended: '2013-11-01T00:00:00+00:00'
  review_date: '2013-11-01T00:00:00+00:00'
  review_decision_date: '2013-11-01T00:00:00+00:00'
  review_decision_event: published
por:
  id: 351-50-29
  terms:
  - type: expression
    normative_status: preferred
    designation: elemento de retenção
  language_code: por
  notes: []
  examples: []
  entry_status: valid
  date_accepted: '2013-11-01T00:00:00+00:00'
  date_amended: '2013-11-01T00:00:00+00:00'
  review_date: '2013-11-01T00:00:00+00:00'
  review_decision_date: '2013-11-01T00:00:00+00:00'
  review_decision_event: published
zho:
  id: 351-50-29
  terms:
  - type: expression
    normative_status: preferred
    designation: 保持元件
  language_code: zho
  notes: []
  examples: []
  entry_status: valid
  date_accepted: '2013-11-01T00:00:00+00:00'
  date_amended: '2013-11-01T00:00:00+00:00'
  review_date: '2013-11-01T00:00:00+00:00'
  review_decision_date: '2013-11-01T00:00:00+00:00'
  review_decision_event: published
```
