### ISSUE TITLE
Concept classification is sometimes in upper case

### ISSUE THREAD

**Issue by skalee** [glossarist/iev-data#188]
Concept classification is not normalized correctly. Sometimes it is in capitalized, whereas it should be one of predefined values, always in lower case.

For example, in Japanese translation for 102-01-01 ("equality") it is "Preferred", whereas the correct value is "preferred":

```yaml
---
termid: 102-01-01
term: equality
# (…)
jpn:
  id: 102-01-01
  terms:
  - type: expression
    normative_status: preferred
    designation: 相当
  - type: expression
    normative_status: preferred
    designation: 等式
  language_code: jpn
  notes: []
  examples: []
  entry_status: valid
  classification: Preferred
  date_accepted: '2007-08-01T00:00:00+00:00'
  date_amended: '2007-08-01T00:00:00+00:00'
  review_date: '2007-08-01T00:00:00+00:00'
  review_decision_date: '2007-08-01T00:00:00+00:00'
  review_decision_event: published
```
