### ISSUE TITLE
Clarification needed on term's classification and designation's normative_status

### ISSUE THREAD

**Issue by skalee** [glossarist/iev-data#191]
Following pseudo YAML illustrates the problem, only relevant fields included:

```yaml
eng:
  terms:
    - type: expression
      normative_status: (always "preferred")
      designation: (taken from TERM column)
    - type: expression
      normative_status: (taken from SYNONYM1STATUS column)
      designation: (taken from SYNONYM1 column)
    - type: expression
      normative_status: (taken from SYNONYM3STATUS column)
      designation: (taken from SYNONYM2 column)
    - type: expression
      normative_status: (taken from SYNONYM3STATUS column)
      designation: (taken from SYNONYM3 column)
    - type: symbol
      designation: (taken from SYMBOLE column)
  classification: (taken from SYNONYM1STATUS column)
```

(Only relevant fields are included. Of course some spreadsheet columns may contain more than one designation, but let's skip that for simplicity.)

What I want to say is that terms `classification` and `normative_status` for the 2nd term are taken from the same SYNONYM1STATUS column, and that smells like a bug. There is no TERMSTATUS column or anything like that in the spreadsheet.

----

cc @ronaldtse
