### ISSUE TITLE
In release package, image path does not match image path specified in definitions

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/iev-data#196]
In 192-02-21:

```yaml
eng:
  id: 192-02-21
  terms:
  - type: expression
    normative_status: preferred
    designation: down time
  definition: |-
    time interval for which the item is in a down state

    image::/assets/images/parts/192/60050-192-F1en.png[Figure 1 - Times related to operation and maintenance]
  language_code: eng
```

Here the image file path is:
```
/assets/images/parts/192/60050-192-F1en.png
```

But it is actually this in the release package (the path differs, filename also differs).
```
images/parts/192/192-F1en.png
```

We need to make this consistent.
