### ISSUE TITLE
Parse the new REPLACES column

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/iev-data#78]
The new REPLACES column indicates which term a term supersedes. 

The value is typically in the form of “XXX-XX-XX:YYYY-MM” where X represents an IEV ID, YYYY the year and MM the month.

We should enact this as a “relationship” just like how the SOURCE gets parsed as relationships. This should be encoded as a “supersedes” relationship.

**Comment by skalee** [comment]
@ronaldtse Just want to double-check: this is relationship between concepts, not their translations, correct?

**Comment by ronaldtse** [comment]
Correct - concepts, not translations. Thanks!

**Comment by skalee** [comment]
Thanks! More questions ahead @ronaldtse.

Concept `102-01-10` supersedes `102-01-10:2007-08`; concept `102-01-20` supersedes `102-01-20:2007-08`; concept `102-05-16` supersedes `102-05-16:2007-08`. Term ID stays the same. Is it okay or some bug in the source?

----

How to represent these relationships? Is following okay?

```
  - type: supersedes
    termid: 102-01-10
    content: 102-01-10:2007-08
```

Or maybe following would be better:

```
  - type: supersedes
    content: 102-01-10:2007-08
```

Or maybe something else?

[Our diagrams](https://raw.githubusercontent.com/glossarist/concept-model/master/images/concept.png) distinguish `ref` and `content`, but honestly, I don't understand the difference.

----

Should I write these relationships at root level (which seems logical) or in the English term (like main authoritative source)? I mean which of following YAML examples is better? This:

```
termid: 102-01-10
term: function
relationships:
  - type: supersedes
    content: 102-01-10:2007-08
```

or maybe this:

```
termid: 102-01-10
term: function
eng:
  relationships:
    - type: supersedes
      content: 102-01-10:2007-08
```

?
